In [1]:
import pandas as pd
import numpy as np
 
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB , BernoulliNB , MultinomialNB
from sklearn.metrics import confusion_matrix , accuracy_score

In [2]:
from pydataset import data
data = data('iris')

In [3]:
data.head(1)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa

In [4]:
x = data.iloc[ : , :-1]
y = data['Species']

In [5]:
x_train , x_test ,y_train ,y_test = train_test_split( x , y , test_size = 0.2 , random_state = 0 )


In [6]:
reg = GaussianNB()
reg.fit(x_train , y_train )

GaussianNB(priors=None, var_smoothing=1e-09)

In [7]:
reg = MultinomialNB()
reg.fit(x_train , y_train )
pred = reg.predict(x_test)
print("The accuracy score is : ", accuracy_score(y_test , pred ) )
print("The Confusion Matrix is : " , confusion_matrix( y_test , pred ) , sep = '\n' )

The accuracy score is :  0.5666666666666667
The Confusion Matrix is : 
[[11  0  0]
 [ 0  0 13]
 [ 0  0  6]]


In [12]:
reg.coef_

array([[-0.70652277, -1.09311227, -1.92826775, -3.64690495],
       [-0.88283036, -1.63431958, -1.21474263, -2.35896543],
       [-0.95530147, -1.74923267, -1.13089036, -2.13157105]])

In [31]:
pred = reg.predict(x_test)
pred

array(['virginica', 'versicolor', 'setosa', 'virginica', 'setosa',
       'virginica', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'setosa', 'versicolor', 'versicolor', 'setosa',
       'setosa', 'virginica', 'versicolor', 'setosa', 'setosa',
       'virginica', 'setosa', 'setosa', 'versicolor', 'versicolor',
       'setosa'], dtype='<U10')

In [35]:
print("The accuracy score is : ", accuracy_score(y_test , pred ) )
print("The Confusion Matrix is : " , confusion_matrix( y_test , pred ) , sep = '\n' )

The accuracy score is :  0.9666666666666667
The Confusion Matrix is : 
[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]


In [ ]:
data

In [36]:
data.corr()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
Sepal.Length      1.000000    -0.117570      0.871754     0.817941
Sepal.Width      -0.117570     1.000000     -0.428440    -0.366126
Petal.Length      0.871754    -0.428440      1.000000     0.962865
Petal.Width       0.817941    -0.366126      0.962865     1.000000

In [23]:
print(y.value_counts())
print()
print(y_test.value_counts())
print()
print(y_train.value_counts())

virginica     50
setosa        50
versicolor    50
Name: Species, dtype: int64

versicolor    13
setosa        11
virginica      6
Name: Species, dtype: int64

virginica     44
setosa        39
versicolor    37
Name: Species, dtype: int64


In [26]:
data['Species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
data['Species'] == ''

In [37]:
ip = pd.read_csv('adult.csv')


In [41]:
ip.head(1)

age workclass  fnlwgt education  education.num marital.status occupation  \
0   90         ?   77053   HS-grad              9        Widowed          ?   

    relationship   race     sex  capital.gain  capital.loss  hours.per.week  \
0  Not-in-family  White  Female             0          4356              40   

  native.country income  
0  United-States  <=50K

In [57]:
c=[]
for i in ip.columns:
    if ip[ip[i].astype(str).str.find('?') != -1].size > 0:
        c.append(i)
c

['workclass', 'occupation', 'native.country']

In [70]:
for i in c:
    ip[i] = ip[i].str.replace('?' , ip[i].mode()[0])

In [71]:
c=[]
for i in ip.columns:
    if ip[ip[i].astype(str).str.find('?') != -1].size > 0:
        c.append(i)
c

[]

In [77]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
cat_c = ip.columns.difference(ip._get_numeric_data().columns)
for i in cat_c:
    ip[i] = lb.fit_transform(ip[i])
    
    

In [84]:
ip.head(1)

age  workclass  fnlwgt  education  education.num  marital.status  \
0   90          3   77053         11              9               6   

   occupation  relationship  race  sex  capital.gain  capital.loss  \
0           9             1     4    0             0          4356   

   hours.per.week  native.country  income  
0              40              38       0

In [94]:
x = ip.iloc[ : , : -1]
y=ip['income']

In [95]:
x_train , x_test ,y_train ,y_test = train_test_split( x , y , test_size = 0.2 , random_state = 0 )


In [96]:
reg = GaussianNB()
reg.fit(x_train , y_train )
pred = reg.predict(x_test)
print("The accuracy score is : ", accuracy_score(y_test , pred ) )
print("The Confusion Matrix is : " , confusion_matrix( y_test , pred ) , sep = '\n' )

The accuracy score is :  0.7979425763856901
The Confusion Matrix is : 
[[4717  249]
 [1067  480]]


In [97]:
reg = BernoulliNB()
reg.fit(x_train , y_train )
pred = reg.predict(x_test)
print("The accuracy score is : ", accuracy_score(y_test , pred ) )
print("The Confusion Matrix is : " , confusion_matrix( y_test , pred ) , sep = '\n' )

The accuracy score is :  0.7286964532473514
The Confusion Matrix is : 
[[3655 1311]
 [ 456 1091]]


In [98]:
reg = MultinomialNB()
reg.fit(x_train , y_train )
pred = reg.predict(x_test)
print("The accuracy score is : ", accuracy_score(y_test , pred ) )
print("The Confusion Matrix is : " , confusion_matrix( y_test , pred ) , sep = '\n' )

The accuracy score is :  0.7881160755412252
The Confusion Matrix is : 
[[4749  217]
 [1163  384]]


In [102]:
print(y.value_counts())
print()
print(y_train.value_counts())
print()
print(y_test.value_counts())

0    24720
1     7841
Name: income, dtype: int64

0    19754
1     6294
Name: income, dtype: int64

0    4966
1    1547
Name: income, dtype: int64
